---
- name: Determine Terraform checksums
  uri:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_SHA256SUMS"
    method: GET
    return_content: true
  register: terraform_checksums

- name: Download Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
    checksum: "sha256:{{ terraform_checksums.content.split('\n')
                 | select('search', 'linux_amd64')
                 | list
                 | first
                 | split(' ')
                 | first }}"
  register: terraform_downloaded
  when: terraform_checksums is defined and terraform_checksums.status == 200

- name: Extract and install Terraform
  unarchive:
    src: "/usr/local/src/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    copy: no
  when: terraform_downloaded is defined and terraform_downloaded is succeeded

- name: Ensure terraform binary is executable
  file:
    path: "/usr/local/bin/terraform"
    mode: "0755"
  when: terraform_downloaded is defined and terraform_downloaded is succeeded

- name: Validate Terraform installation
  command: terraform version
  register: terraform_version_output
  changed_when: false
  when: terraform_downloaded is defined and terraform_downloaded is succeeded

- name: Show installed Terraform version
  debug:
    msg: "{{ terraform_version_output.stdout }}"
  when: terraform_version_output is defined
